FROM node:12 as build 
WORKDIR /app
COPY ./app .
RUN npm install
RUN npm run build
FROM nginx:alpine
COPY --from=build /app/dist/** /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 8081
CMD ["nginx","-g", "daemon off;"]
